version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin@2024031805
    container_name: jellyfin
    ports:
        - '8096:8096'
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - radarr_movies:/home/movies
      - sonarr_tvseries:/home/tv
    restart: unless-stopped
  jellyseerr:
    image: fallenbagel/jellyseerr@1.7.0
    container_name: jellyseerr
    environment:
      - 'LOG_LEVEL=debug'
      - 'TZ=Europe/Warsaw'
    ports:
      - '5055:5055'
    volumes:
      - jellyfin_config:/app/config
      - radarr_movies:/home/movies
      - sonarr_tvseries:/home/tv
    restart: unless-stopped
  prowlarr:
    image: linuxserver/prowlarr@amd64-1.14.3-main
    volumes:
      - prowlarr_config:/config
    environment:
      - 'PUID=0'
      - 'PGID=65534'
      - 'TZ=Europe/Warsaw'
    ports:
      - '9696:9696'
    restart: unless-stopped
  sonarr:
    build:
      dockerfile: sonarr.dockerfile
    container_name: sonarr
    volumes:
      - sonarr_config:/config
      - sonarr_tvseries:/home/tv
      - qbittorrent_downloads:/downloads
    environment:
      - 'PUID=0'
      - 'PGID=65534'
      - 'TZ=Europe/Warsaw'
    ports:
      - '8989:8989'
    restart: unless-stopped
  radarr:
    build:
      dockerfile: radarr.dockerfile
    container_name: radarr
    ports:
      - '7878:7878'
    environment:
      - 'PUID=0'
      - 'PGID=65534'
    volumes:
      - radarr_movies:/home/movies
      - radarr_config:/config
      - qbittorrent_downloads:/downloads
    restart: unless-stopped
  bazarr:
    build:
      dockerfile: bazarr.dockerfile
    container_name: bazarr
    environment:
      - 'PUID=0'
      - 'PGID=65534'
    volumes:
      - bazarr_config:/config
      - radarr_movies:/home/movies
      - sonarr_tvseries:/home/tv
    ports:
      - 6767:6767
    restart: unless-stopped
  qbittorrent:
    image: linuxserver/qbittorrent@4.6.3
    container_name: qbittorrent
    volumes:
      - qbittorrent_downloads:/downloads
    restart: unless-stopped
# todo:
#   - flaresolverr
#   - kopia

volumes:
  jellyfin_config: {}
  jellyfin_cache: {}
  prowlarr_config: {}
  sonarr_config: {}
  radarr_config: {}
  bazarr_config: {}
  radarr_movies: {}
  sonarr_tvseries: {}
  qbittorrent_downloads: {}
